D3\AnalyticsBundle\Entity\DataSource:
    exclusion_policy: ALL
    properties :
      id :
        expose : true
      name :
        expose : true
      fileName :
        expose : true
      fileExtension:
        expose: true
      dataStores:
        expose: false



