D3\AnalyticsBundle\Entity\Visualization:
    exclusion_policy: ALL
    properties :
      id :
        expose : true
      name :
        expose : true
      description :
        expose : true
      visualizationTypeId :
        expose : true
      isStarred :
        expose : true
      isActive :
        expose : true
      chartData:
        expose: true
      creationDate:
        expose: true
      updateDate:
        expose: true
      collections:
        expose: false
      dataSources:
        expose: true



