################################################################################
# HOME

D3AnalyticsBundle_index:
  pattern: /
  defaults: { _controller: D3AnalyticsBundle:Front:index }
  requirements:
    _method: GET


D3AnalyticsBundle_about:
  pattern: /about
  defaults: { _controller: D3AnalyticsBundle:Front:about }
  requirements:
    _method: GET


D3AnalyticsBundle_contact:
  pattern: /contact
  defaults: { _controller: D3AnalyticsBundle:Front:contact }
  requirements:
    _method: GET|POST

