
################################################################################
#
# HOME
#
################################################################################

D3AnalyticsBundle_index:
    pattern: /
    defaults: { _controller: D3AnalyticsBundle:Front:index }
    requirements:
        _method: GET

D3AnalyticsBundle_about:
    pattern: /about
    defaults: { _controller: D3AnalyticsBundle:Front:about }
    requirements:
        _method: GET



################################################################################
#
# DATA SOURCE
#
################################################################################

datasource:
    pattern:  /
    defaults: { _controller: "D3AnalyticsBundle:DataSource:index" }

datasource_show:
    pattern:  /{id}/show
    defaults: { _controller: "D3AnalyticsBundle:DataSource:show" }

datasource_new:
    pattern:  /new
    defaults: { _controller: "D3AnalyticsBundle:DataSource:new" }

datasource_create:
    pattern:  /create
    defaults: { _controller: "D3AnalyticsBundle:DataSource:create" }
    requirements: { _method: post }

datasource_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "D3AnalyticsBundle:DataSource:edit" }

datasource_update:
    pattern:  /{id}/update
    defaults: { _controller: "D3AnalyticsBundle:DataSource:update" }
    requirements: { _method: post|put }

datasource_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "D3AnalyticsBundle:DataSource:delete" }
    requirements: { _method: post|delete }





