_wdt:
  resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
  prefix:   /_wdt

_profiler:
  resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
  prefix:   /_profiler

_configurator:
  resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
  prefix:   /_configurator

_main:
  resource: routing.yml


d3_analytics:
  resource: "@D3AnalyticsBundle/Resources/config/routing.yml"
  prefix: /


d3_analytics_api:
  resource: "@D3AnalyticsBundle/Resources/config/routing_api.yml"
  prefix: /api




